# App Engine configuration for the interface
runtime: python310
instance_class: F1

# Automatic scaling settings
automatic_scaling:
  max_instances: 1
  min_instances: 0
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.6

# Request handlers
handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always

# Environment variables
env_variables:
  CLOUD_RUN_URL: "https://phindllama-trading-system-u5d2kummnq-uc.a.run.app"
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
