# app.yaml
runtime: python39
instance_class: F2
automatic_scaling:
  max_instances: 5
  min_instances: 1
  max_idle_instances: 3
  min_idle_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: 500ms

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

env_variables:
  PHINDLLAMA_MODEL: "phindllama-7b"
  WEBUI_PORT: "5000"
  DATABASE_URL: "postgresql://user:password@/database"
  METRICS_DB_URL: "postgresql://user:password@/metrics"
