name: Deploy and Monitor
on: [push, schedule]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        chmod +x setup.sh
        ./setup.sh
        nohup ./dashboard.sh &
    - name: Verify deployment
      run: |
        curl --retry 5 --retry-delay 10 --retry-connrefused http://localhost:8501