runtime: python39
instance_class: F2
entrypoint: gunicorn -b : main:app

basic_scaling:
  max_instances: 5
  idle_timeout: 10m

handlers:
- url: /.*
  script: auto
  secure: always

env_variables:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
