# App Engine configuration
runtime: python39
instance_class: F2

# The entry point for the application
entrypoint: gunicorn -b :$PORT main:app

# Basic scaling settings
basic_scaling:
  max_instances: 5
  idle_timeout: 10m

# Request handlers
handlers:
- url: /.*
  script: auto
  secure: always

# Environment variables
env_variables:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
